### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by IRonicBruh** [kwpugh/gobber#48]
---- Minecraft Crash Report ----
// You're mean.

Time: 5/4/20 1:26 AM
Description: Ticking entity

java.lang.NullPointerException: Registry Object not present: ring_of_repair:ring_of_repair
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at com.kwpugh.ring_of_repair.RepairTickHandler.onPlayerTick(RepairTickHandler.java:35) ~[?:1.1.23] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_89_RepairTickHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:206) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:PlayerEntity,xf:fml:backpacked:player_init_hook,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:caelus:coremodone,xf:fml:randompatches:RandomPatches ClientPlayerEntity Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:179) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$8923/1594362867.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:149) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1399) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.45.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1040477753.call(Unknown Source) [forge-1.15.2-31.1.45.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91)
	at com.kwpugh.ring_of_repair.RepairTickHandler.onPlayerTick(RepairTickHandler.java:35)
	at net.minecraftforge.eventbus.ASMEventHandler_89_RepairTickHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:206)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:179)
	at net.minecraft.client.world.ClientWorld$$Lambda$8923/1594362867.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 1114
	Entity Name: DayzIn
	Entity's Exact location: 67.50, 63.00, -248.50
	Entity's Block location: World: (67,63,-249), Chunk: (at 3,3,7 in 4,-16; contains blocks 64,0,-256 to 79,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:149)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['DayzIn'/1114, l='MpServer', x=67.50, y=63.00, z=-248.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -2781876637283508092
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (67,63,-249), Chunk: (at 3,3,7 in 4,-16; contains blocks 64,0,-256 to 79,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 6750548 game time, 2818218 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1040477753.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 544318664 bytes (519 MB) / 2123366400 bytes (2025 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.45.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.45.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.12.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.45
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.1
	Mod List: 
		inftrading_1.15.2-1.0.jar Infinite Trading {inftrading@1.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		glasscutter-1.0.1-1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		doubledoors_1.15-2.0.jar Double Doors {doubledoors@2.0 DONE}
		roughmobsrevamped-1.15.2-4.1.1.jar Rough Mobs Revamped {roughmobsrevamped@version DONE}
		CraftingAutomat-MC1.15.2-1.2.1.jar Crafting Automat {craftingautomat@1.2.1 DONE}
		PreGenForge-0.1.0-mc1.15.2.jar PreGenForge {pregenforge@0.1.0 DONE}
		DeathCounter-1.15.2-1.2.0.jar Death Counter {deathcounter@1.2.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		caelus-FORGE-1.15.2-2.0-beta2.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta2 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		BetterStorageToo-1.15.2-5.0.1.0.jar BetterStorageToo {betterstorage@1.15.2-5.0.1.0 DONE}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		glassential-forge-1.15.2-1.1.2.jar Glassential {glassential@1.1.2 DONE}
		TerraForged-1.15.2-0.0.13.jar TerraForged {terraforged@0.0.13 DONE}
		RingOfRepair-1.15.2-1.1.23.jar Ring of Repair {ring_of_repair@1.1.23 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		MutantBeasts-1.15.2-1.0.5.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.5 DONE}
		FarmingForBlockheads_1.15.2-6.1.2.jar Farming for Blockheads {farmingforblockheads@6.1.2 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		Coins-1.15.2-1.0.1.jar Coins {coins@1.0.1 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.8.jar The Endergetic Expansion {endergetic@1.2.8 DONE}
		guardvillagers-1.15.2-1.0.6.jar Guard Villagers {guardvillagers@1.0.6 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		mapperbase-1.15.2-1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 DONE}
		dragondropsel_1.15.2-1.0.jar Dragon Drops Elytra {dragondropsel@1.0 DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		forge-1.15.2-31.1.45-universal.jar Forge {forge@31.1.45 DONE}
		SimpleOres2-1.15.2-2.1.5.1.jar Simple Ores {simpleores@1.15.2-2.1.5.1 DONE}
		extendedfurnace-2.2.jar Extended Furnace {extendedfurnace@2.2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		anviltweaks-2.3.jar Anvil Tweaks {anviltweaks@2.3 DONE}
		forge-1.15.2-31.1.45-client.jar Minecraft {minecraft@1.15.2 DONE}
		repurposedstructures-1.15.2-1.4.0.jar Repurposed Structures {repurposed_structures@1.15.2-1.4.0 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		embellishcraft-1.15.2-2.2.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.15.2-4.6.1+49.jar Silent Lib {silentlib@4.6.1+49 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		concreteconversion-1.15.2-4.1.0.0.jar Concrete Conversion {concreteconversion@1.15.2-4.1.0.0 DONE}
		playerhopper-1.15-1.3.jar Player Hopper {playerhopper@1.15-1.3 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		GeneticAnimals-0_5_3.jar Genetic Animals {eanimod@0_5_3 DONE}
		extragolems-10.1.1.jar Extra Golems {golems@10.1.1 DONE}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		horse_colors-1.15.2-1.1.3.jar Realistic Horse Genetics {horse_colors@1.15.2-1.1.2 DONE}
		performant-1.15-2.09m.jar Performant {performant@2.09m DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		harvest-1.15.2-1.0.1.jar Harvest {harvest@1.0.1 DONE}
		Gobber2-1.15.2-2.2.90.jar Gobber 2 {gobber2@2.2.90 DONE}
		grindr-1.15.2-0.0.1.5.jar Grindr {grindr@1.15.2-0.0.1.5 DONE}
		AttainedDrops-1.15.2-6.0.7.jar Attained Drops {attained_drops@6.0.7 DONE}
		PowderPower-1.15.2-3.1.61.jar Powder Power {powder_power@3.1.61 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		Project MMO-1.15-2.25.1.jar Project MMO {pmmo@2.25.1 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		Biomes_You_Go-0.3.3-BETA.jar Oh The Biomes You'll Go {byg@0.2.1 DONE}
		Charm-1.15.2-1.5.7.jar Charm {charm@1.15.2-1.5.7 DONE}
		Strange-1.15.2-1.0.0-beta.3.jar Strange {strange@1.15.2-1.0.0-beta.3 DONE}
		classicbar-3.0.2.jar Classic Bar {classicbar@3.0.2 DONE}
		EnderMail-1.15.2-1.1.0.jar Ender Mail {endermail@1.15.2-1.1.0 DONE}
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 DONE}
		farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 DONE}
	Launched Version: forge-31.1.45
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.74, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/1.15.2-r1.zip, file/Clear Water - 1.13+.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz

**Comment by kwpugh** [comment]
Please update to the latest version of ring_of_repair and see if it still happens.

**Comment by kwpugh** [comment]
Also, may want to update to a more recent Forge, your on .45 and .74 is the latest.  Lots of fix since then.

**Comment by kwpugh** [comment]
Cannot replicate, closing until reoccurrence.
