### ISSUE TITLE
[1.16.3]  Gobber2-1.16.3-2.3.0.jar

### ISSUE THREAD

**Issue by HonestAngel** [kwpugh/gobber#65]
forge-1.16.3-34.0.1.jar
Failure message: Gobber 2 (gobber2) encountered an error during the common_setup event phase

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/11/20 10:48 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4791/1534884314.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4427/1161734134.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.0.1.jar:34.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$440/238308051.call(Unknown Source) [forge-1.16.3-34.0.1.jar:34.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218) ~[guava-21.0.jar:?] {}
-- MOD premium_wood --
Details:
	Mod File: premium-wood-1.16.3-1.3.0.jar
	Failure message: Premium Wood (premium_wood) encountered an error during the common_setup event phase
		java.lang.UnsupportedOperationException: null
	Mod Version: 1.3.0
	Mod Issue URL: https://gitlab.com/modding-legacy/premium-wood/issues
	Exception message: java.lang.UnsupportedOperationException
Stacktrace:
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218) ~[guava-21.0.jar:?] {}
	at com.legacy.premium_wood.world.GenUtil.addFeature(GenUtil.java:33) ~[?:1.3.0] {re:classloading}
	at com.legacy.premium_wood.registry.PremiumFeatures.addTrees(PremiumFeatures.java:57) ~[?:1.3.0] {re:classloading}
	at com.legacy.premium_wood.PremiumWoodMod$$Lambda$4584/2018790453.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at com.legacy.premium_wood.PremiumWoodMod.commonInit(PremiumWoodMod.java:44) ~[?:1.3.0] {re:classloading}
	at com.legacy.premium_wood.PremiumWoodMod$$Lambda$3226/492914943.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2895/826245889.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$null$4(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3099/791109656.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3085/1069131391.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- MOD gobber2 --
Details:
	Mod File: Gobber2-1.16.3-2.3.0.jar
	Failure message: Gobber 2 (gobber2) encountered an error during the common_setup event phase
		java.lang.UnsupportedOperationException: null
	Mod Version: 2.3.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.UnsupportedOperationException
Stacktrace:
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218) ~[guava-21.0.jar:?] {}
	at com.kwpugh.gobber2.world.OreGenerator.addFeatureToBiome(OreGenerator.java:91) ~[?:2.3.0] {re:classloading}
	at com.kwpugh.gobber2.world.OreGenerator.addFeatures(OreGenerator.java:55) ~[?:2.3.0] {re:classloading}
	at com.kwpugh.gobber2.Gobber2.modSetup(Gobber2.java:54) ~[?:2.3.0] {re:classloading}
	at com.kwpugh.gobber2.Gobber2$$Lambda$3770/1840706013.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2895/826245889.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$null$4(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3099/791109656.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3085/1069131391.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 100041080 bytes (95 MB) / 2374500352 bytes (2264 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.0.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.0.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.0.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.0.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.0.1.jar fml TRANSFORMATIONSERVICE 
	FML: 34.0
	Forge: net.minecraftforge:34.0.1
	FML Language Providers: 
		javafml@34.0
		minecraft@1
	Mod List: 
		forge-1.16.3-34.0.1-client.jar Minecraft {minecraft@1.16.3 SIDED_SETUP}
		Resynth-5.2.0-[Minecraft-Forge-1.16.3].jar Resynth {resynth@5.2.0 SIDED_SETUP}
		Variant16x-1.16.3-v0.15.4_alpha_pre1.jar Variant16x {variant16x@0.15.4_alpha_pre1 SIDED_SETUP}
		SaveYourPets-1.16.2-1.0.0.4.jar Save Your Pets {syp@1.0.0.4 SIDED_SETUP}
		rare-ice-0.2.2.jar Rare Ice {rare-ice@version SIDED_SETUP}
		packedup-1.0.18-mc1.16.3.jar PackedUp {packedup@1.0.18 SIDED_SETUP}
		FallingTree-Forge-1.16.3-2.3.1.jar Falling Tree {falling_tree@2.3.1 SIDED_SETUP}
		tesseract-1.0.12-mc1.16.3.jar Tesseract {tesseract@1.0.12 SIDED_SETUP}
		ceramicshears-1.3.2-1.16.1+.jar Ceramic Shears {ceramicshears@1.3.2-1.16.1+ SIDED_SETUP}
		Tiny-Coal-1.16.3-1.0.0.jar Tiny Coal {tinycoal@1.0.0 SIDED_SETUP}
		BetterCaves-1.16.2-1.0.2.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.2 SIDED_SETUP}
		NeverNeededOrWanted-1.16.3-1.0.4.jar Never Needed Or Wanted {nnow@1.16.3-1.0.4 SIDED_SETUP}
		itemcollectors-1.0.5-mc1.16.3.jar Item Collectors {itemcollectors@1.0.5 SIDED_SETUP}
		ResourcefulTools-1.16.3-1.2.3.jar Resourceful Tools {resourceful_tools@1.2.3 SIDED_SETUP}
		sit-1.16.2-v1.3.jar Sit {sit@v1.3 SIDED_SETUP}
		premium-wood-1.16.3-1.3.0.jar Premium Wood {premium_wood@1.3.0 ERROR}
		BridgeMaker-1.16.3-1.0.0.jar Bridge Maker {bridge_maker@1.0.0 SIDED_SETUP}
		Gobber2-1.16.3-2.3.0.jar Gobber 2 {gobber2@2.3.0 ERROR}
		tubesreloaded-1.16.3-1.4.0.1.jar Tubes Reloaded {tubesreloaded@1.16.3-1.4.0.1 SIDED_SETUP}
		Bookshelf-1.16.3-8.0.3.jar Bookshelf {bookshelf@8.0.3 SIDED_SETUP}
		PowderPower-1.16.3-3.2.4.jar Powder Power {powder_power@3.2.4 SIDED_SETUP}
		wormhole-1.0.9-mc1.16.3.jar Wormhole (Portals) {wormhole@1.0.9 SIDED_SETUP}
		connectedglass-1.0.6-mc1.16.3.jar Connected Glass {connectedglass@1.0.6 SIDED_SETUP}
		CauldronRecipes-1.16.3-4.0.1.jar CauldronRecipes {cauldronrecipes@4.0.1 SIDED_SETUP}
		trashcans-1.0.3-mc1.16.3.jar Trash Cans {trashcans@1.0.3 SIDED_SETUP}
		ironcoals-2.2.0.jar Iron Coals {ironcoals@2.2.0	 SIDED_SETUP}
		forge-1.16.3-34.0.1-universal.jar Forge {forge@34.0.1 SIDED_SETUP}
		VendingMachine-1.16.2-1.0.0.3.jar Vending Machine {vm@1.0.0.3 SIDED_SETUP}
		RevampedWolf-1.16.3-0.6.2.jar RevampedWolf {revampedwolf@1.16.3-0.6.2 SIDED_SETUP}

**Comment by HonestAngel** [comment]
sorry about that I had the wrong window open and I wasn't looking at the name of the mod.

**Comment by kwpugh** [comment]
Add a check for mutable list.
