### ISSUE TITLE
[1.16.3] Crash when creeper explodes?

### ISSUE THREAD

**Issue by SkylordSilver** [kwpugh/gobber#69]
Every other mob seems fine when they attack, was able to recreate the crash, and only the creeper exploding causes it. This is the report from the first crash.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/20/20 9:16 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.kwpugh.gobber2.util.handlers.ForgeEventSubscriber.onKillingLootEvent(ForgeEventSubscriber.java:100) ~[?:2.3.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_176_ForgeEventSubscriber_onKillingLootEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:367) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:360) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {}
	at java.util.function.Predicate$$Lambda$446/248495761.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.0+0] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1194) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:630) ~[?:?] {re:classloading}
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:250) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_230546_a_(ServerWorld.java:1033) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.World.func_217385_a(World.java:566) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.monster.CreeperEntity.func_146077_cc(CreeperEntity.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:146) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.server.ServerWorld$$Lambda$9746/2016470838.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$9359/2111628226.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.kwpugh.gobber2.util.handlers.ForgeEventSubscriber.onKillingLootEvent(ForgeEventSubscriber.java:100) ~[?:2.3.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_176_ForgeEventSubscriber_onKillingLootEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:367) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:360) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {}
	at java.util.function.Predicate$$Lambda$446/248495761.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.0+0] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1194) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:630) ~[?:?] {re:classloading}
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:250) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_230546_a_(ServerWorld.java:1033) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.World.func_217385_a(World.java:566) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.monster.CreeperEntity.func_146077_cc(CreeperEntity.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:146) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.server.ServerWorld$$Lambda$9746/2016470838.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 7
	Entity Name: Creeper
	Entity's Exact location: 243.70, 38.00, -8.95
	Entity's Block location: World: (243,38,-9), Chunk: (at 3,2,7 in 15,-1; contains blocks 240,0,-16 to 255,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['SkylordSilver'/184, l='ServerLevel[1.16.3 Forged Survival]', x=243.47, y=42.00, z=-5.82]]
	Chunk stats: ServerChunkCache: 3025
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,63,0), Chunk: (at 0,3,0 in 14,0; contains blocks 224,0,0 to 239,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 35775 game time, 35775 day time
	Level name: 1.16.3 Forged Survival
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 138478 (now: false), thunder time: 144111 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$9359/2111628226.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2185542496 bytes (2084 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.0.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.0.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.0.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.0.9.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.0.9.jar fml TRANSFORMATIONSERVICE 
	FML: 34.0
	Forge: net.minecraftforge:34.0.9
	FML Language Providers: 
		javafml@34.0
		minecraft@1
	Mod List: 
		forge-1.16.3-34.0.9-client.jar Minecraft {minecraft@1.16.3 DONE}
		Ma-Enchants-1.16.3-3.4.0.jar Ma Enchants {ma-enchants@1.16.3-3.4.0 DONE}
		ToLaserBlade-1.16.3-4.0.0.0.jar ToLaserBlade {tolaserblade@1.16.3-4.0.0.0 DONE}
		EasySteel-1.16.3-1.2.4.jar Easy Steel & More {easy_steel@1.2.4 DONE}
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 DONE}
		ImmersiveEngineering-1.16.3-4.0.1-121.jar Immersive Engineering {immersiveengineering@1.16.3-4.0.1-118 DONE}
		useful_railroads-1.16.3-1.4.4.31.jar Useful Railroads {usefulrailroads@1.4.4.31 DONE}
		SilentLib-1.16.2-4.8.0+60.jar Silent Lib {silentlib@4.8.0+60 DONE}
		ToolStats-1.16.3-4.0.1.jar ToolStats {toolstats@4.0.1 DONE}
		Lollipop-1.16.3-3.2.0.jar Lollipop {lollipop@3.2.0 DONE}
		practicaltools-1.16.3-1.8.jar Practical Tools {practicaltools@1.16.3-1.8 DONE}
		ava-1.4.6.jar A.V.A - Alliance of Valiant Arms {ava@1.4.6 DONE}
		jei-1.16.3-7.3.2.30.jar Just Enough Items {jei@7.3.2.29 DONE}
		masonry-1.16.3-0.3.6.jar Masonry {masonry@NONE DONE}
		tesseract-1.0.12-mc1.16.3.jar Tesseract {tesseract@1.0.12 DONE}
		simplybackpacks-1.16.3-1.4.12.jar Simply Backpacks {simplybackpacks@1.16.3-1.4.12 DONE}
		caelus-forge-1.16.2-2.0.0.0.jar Caelus API {caelus@1.16.2-2.0.0.0 DONE}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 DONE}
		AzureDooms-Doom-Mod-1.16.3-3.1.2.jar Azuredooms Doom Mod {doomweapon@3.1.2 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		curios-forge-1.16.3-4.0.1.0.jar Curios API {curios@1.16.3-4.0.1.0 DONE}
		BetterCaves-1.16.2-1.0.2.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.2 DONE}
		glassential-forge-1.16.3-1.1.5.jar Glassential {glassential@1.1.5 DONE}
		SurvivalPlus-1.16.3-0.1.3b.jar SurvivalPlus {survivalplus@0.1.3b DONE}
		Powah-1.16.3-2.3.0.jar Powah {powah@2.3.0 DONE}
		DoubleSlabs-1.16-3.4.9.jar Double Slabs {doubleslabs@3.4.9 DONE}
		InventoryHud_1.16.3.forge-3.1.0.jar Inventory HUD+(Forge edition) {inventoryhud@3.1.0 DONE}
		Gobber2-1.16.3-2.3.9.jar Gobber 2 {gobber2@2.3.8 DONE}
		structurize-0.13.67-ALPHA.jar Structurize {structurize@0.13.67-ALPHA DONE}
		Bookshelf-1.16.3-8.1.7.jar Bookshelf {bookshelf@8.1.7 DONE}
		BedBenefits-1.16.3-3.0.1.jar BedBenefits {bedbenefits@3.0.1 DONE}
		BotanyPots-1.16.3-5.0.1.jar BotanyPots {botanypots@5.0.1 DONE}
		expandedstorage-3.0.4+1.16.3.jar Expanded Storage {expandedstorage@3.0.4 DONE}
		u_team_core-1.16.3-3.1.9.181.jar U Team Core {uteamcore@3.1.9.181 DONE}
		minecolonies-0.13.261-ALPHA-universal.jar Minecolonies {minecolonies@0.13.261-ALPHA DONE}
		simpleplanes-1.16.3-3.0.0.2.jar Simple Planes {simpleplanes@1.16.3-3.0.0.2 DONE}
		curiouselytra-forge-1.16.2-4.0.0.0.jar Curious Elytra {curiouselytra@1.16.2-4.0.0.0 DONE}
		forgemod_VoxelMap-1.10.11_for_1.16.3.jar VoxelMap {voxelmap@1.10.11 DONE}
		BetterBurning-1.16.3-4.0.2.jar BetterBurning {betterburning@4.0.2 DONE}
		forge-1.16.3-34.0.9-universal.jar Forge {forge@34.0.9 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 DONE}
		SolarGeneration-1.16.3-2.2.0.jar Solar Generation {solargeneration@2.2.0 DONE}
		ScalingHealth-1.16.3-4.0.0+0.jar Scaling Health {scalinghealth@4.0.0+0 DONE}
		DarkPaintings-1.16.3-4.0.2.jar DarkPaintings {darkpaintings@4.0.2 DONE}
		TrinityWeapons-1.16.2-1.5.0.jar TrinityWeapons {trinity@1.5.0 DONE}
		MysticalAgriculture-1.16.3-4.1.0.jar Mystical Agriculture {mysticalagriculture@4.1.0 DONE}
		corpse-1.16.3-1.0.2.jar Corpse {corpse@1.16.3-1.0.2 DONE}

**Comment by kwpugh** [comment]
What were you doing to cause this to happen?   I cannot replicate it.

**Comment by SkylordSilver** [comment]
I'm playing survival, just mining, when it came from behind me and i smacked it with a stone sword, and right when he exploded, game froze then crashed.

**Comment by SkylordSilver** [comment]
I'm gonna try a different version of gobber just to see if, by chance, its just the latest version doing this.

**Comment by kwpugh** [comment]
Same as #72
