### ISSUE TITLE
[1.17] Players w/ Ring of Farmer kicked from server

### ISSUE THREAD

**Issue by micahflack** [kwpugh/gobber#98]
As the title states, whenever a player's inventory contains the Ring of the Farmer they are kicked from the server.

The error generated by the server:
`
[STDOUT]: Negative index in crash report handler (0/10)
net.minecraft.class_148: Ticking player
at net.minecraft.class_3222.method_14226(class_3222.java:533) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[intermediary-server.jar:?]
at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:904) ~[intermediary-server.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:334) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArithmeticException
`

This is with Fabric Loader 0.7.4 and Fabric API 0.35.2

Had to use following command before player was able to join again.
`
clear <player> gobber2:gobber2_ring_farmer 1
`

**Comment by kwpugh** [comment]
fixed in v2.4.14 that I just pushed to curse forge.
